# This file was generated by GoReleaser. DO NOT EDIT.
cask "slackctl-cli" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "9b8ec6bf1c0245b4d2890c45cca2967f5dc82c80155570bef7e1d173907f5cb6"
      url "https://github.com/jjuanrivvera/slackctl/releases/download/v#{version}/slackctl_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "865e67a91b19101c34aae9fdbfbd348fabb3963642c0294f42fb80b4b8bc9992"
      url "https://github.com/jjuanrivvera/slackctl/releases/download/v#{version}/slackctl_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "8a929d0af71dc12ea16f67f85de048d0e5b5583d4e11741e4860ec6d0dfd3fb5"
      url "https://github.com/jjuanrivvera/slackctl/releases/download/v#{version}/slackctl_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "0825f9ae691a6c0d3318fade22f0ee7fd799e27072002846dfc3ea24af964115"
      url "https://github.com/jjuanrivvera/slackctl/releases/download/v#{version}/slackctl_#{version}_linux_arm64.tar.gz"
    end
  end

  name "slackctl-cli"
  desc ""
  homepage "https://github.com/jjuanrivvera/slackctl"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "slackctl"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/slackctl"]
  end

  # No zap stanza required

end
