# This file was generated by GoReleaser. DO NOT EDIT.
cask "slackctl-cli" do
  version "0.3.1"

  on_macos do
    on_intel do
      sha256 "ccc04e9e9597a6a1259823f85b90a5a14f424a3b6d3d4b3a4fc8a92c1277bedd"
      url "https://github.com/jjuanrivvera/slackctl/releases/download/v#{version}/slackctl_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "bdf2ad401399728cc1f790b2a53e96b13b758615c82b5f25a885ae5dca8a5b26"
      url "https://github.com/jjuanrivvera/slackctl/releases/download/v#{version}/slackctl_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "490c9b28ed0c9da8430eee26b1f483e0b4a0a0eb59f26c97c5e39ac444ea248a"
      url "https://github.com/jjuanrivvera/slackctl/releases/download/v#{version}/slackctl_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "ee9f5821b1ee0e42b05817c897e4098dddf966590619fb97dad7d02573bab784"
      url "https://github.com/jjuanrivvera/slackctl/releases/download/v#{version}/slackctl_#{version}_linux_arm64.tar.gz"
    end
  end

  name "slackctl-cli"
  desc ""
  homepage "https://github.com/jjuanrivvera/slackctl"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "slackctl"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/slackctl"]
  end

  # No zap stanza required

end
