# This file was generated by GoReleaser. DO NOT EDIT.
cask "slackctl-cli" do
  version "0.3.2"

  on_macos do
    on_intel do
      sha256 "4fd54ea8ae201dca5981b42e4198849ab532b3570cf5dc17148a3cd22e340f4f"
      url "https://github.com/jjuanrivvera/slackctl/releases/download/v#{version}/slackctl_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "870c225d37bae04a1a30bcbe69761690202fec523116f224b7a1c3755ee2d5a0"
      url "https://github.com/jjuanrivvera/slackctl/releases/download/v#{version}/slackctl_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "fc18aab7bce5a5322472d2c2cb8636ee62f745de9b822541366d2a56aaa6e834"
      url "https://github.com/jjuanrivvera/slackctl/releases/download/v#{version}/slackctl_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "f776b3b65e71c794bda8cbb0ccea644de61a5d4942d68c2526a950969bb2b7a2"
      url "https://github.com/jjuanrivvera/slackctl/releases/download/v#{version}/slackctl_#{version}_linux_arm64.tar.gz"
    end
  end

  name "slackctl-cli"
  desc ""
  homepage "https://github.com/jjuanrivvera/slackctl"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "slackctl"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/slackctl"]
  end

  # No zap stanza required

end
